# Generated by Django 5.0.2 on 2024-02-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmedia',
            name='file',
            field=models.FileField(blank=True, upload_to='uploaded_files'),
        ),
    ]
